name: yarn-lock
version: 0.3.1
github: Profpatsch/yarn-lock
license: MIT
license-file: LICENSE
synopsis: Represent and parse yarn.lock files
description:
  Types and parser for the lock file format of the npm successor yarn.
  All modules should be imported qualified.
author: Profpatsch
maintainer: mail@profpatsch.de
category: Data
extra-source-files:
  - CHANGELOG.md

ghc-options:
  - -Wall

dependencies:
  - base >= 4.9
  - containers
  - text
  - megaparsec == 5.* || == 6.*
  - protolude >= 0.1
  - either == 4.*

library:
  source-dirs: src

tests:
  yarn-lock-tests:
    main: Test.hs
    source-dirs: tests
    dependencies:
      - yarn-lock
      - ansi-wl-pprint >= 0.6
      - tasty >= 0.11
      - tasty-th >= 0.1.7
      - tasty-hunit >= 0.9
      - tasty-quickcheck >= 0.8
      - protolude
      - neat-interpolation >= 0.3